"""Enforce positive collection item quantities

Revision ID: 20b1e532935b
Revises: 1afac97d02e3
Create Date: 2026-09-04 07:46:13.323474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20b1e532935b'
down_revision: Union[str, Sequence[str], None] = '1afac97d02e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint('ck_collection_items_expected_quantity_positive', 'collection_items', 'expected_quantity > 0')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_collection_items_expected_quantity_positive', 'collection_items', type_='check')
    # ### end Alembic commands ###
