"""Create assets table

Revision ID: 29f0f813dc72
Revises: 3bcbad1072c2
Create Date: 2026-08-31 20:22:56.226956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29f0f813dc72'
down_revision: Union[str, Sequence[str], None] = '3bcbad1072c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('asset_code', sa.String(length=30), nullable=False),
    sa.Column('serial_number', sa.String(length=150), nullable=True),
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.Column('collection_item_id', sa.Integer(), nullable=True),
    sa.Column('asset_category', sa.String(length=100), nullable=False),
    sa.Column('manufacturer', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=150), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=40), server_default='received', nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('received_by', sa.String(length=150), nullable=True),
    sa.Column('receiving_notes', sa.Text(), nullable=True),
    sa.Column('data_wipe_status', sa.String(length=40), server_default='not_started', nullable=False),
    sa.Column('data_wipe_method', sa.String(length=100), nullable=True),
    sa.Column('data_wipe_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data_wipe_reference', sa.String(length=100), nullable=True),
    sa.Column('final_disposition', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['collection_item_id'], ['collection_items.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_asset_category'), 'assets', ['asset_category'], unique=False)
    op.create_index(op.f('ix_assets_asset_code'), 'assets', ['asset_code'], unique=True)
    op.create_index(op.f('ix_assets_collection_id'), 'assets', ['collection_id'], unique=False)
    op.create_index(op.f('ix_assets_collection_item_id'), 'assets', ['collection_item_id'], unique=False)
    op.create_index(op.f('ix_assets_data_wipe_status'), 'assets', ['data_wipe_status'], unique=False)
    op.create_index(op.f('ix_assets_final_disposition'), 'assets', ['final_disposition'], unique=False)
    op.create_index(op.f('ix_assets_manufacturer'), 'assets', ['manufacturer'], unique=False)
    op.create_index(op.f('ix_assets_model'), 'assets', ['model'], unique=False)
    op.create_index(op.f('ix_assets_serial_number'), 'assets', ['serial_number'], unique=False)
    op.create_index(op.f('ix_assets_status'), 'assets', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assets_status'), table_name='assets')
    op.drop_index(op.f('ix_assets_serial_number'), table_name='assets')
    op.drop_index(op.f('ix_assets_model'), table_name='assets')
    op.drop_index(op.f('ix_assets_manufacturer'), table_name='assets')
    op.drop_index(op.f('ix_assets_final_disposition'), table_name='assets')
    op.drop_index(op.f('ix_assets_data_wipe_status'), table_name='assets')
    op.drop_index(op.f('ix_assets_collection_item_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_collection_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_asset_code'), table_name='assets')
    op.drop_index(op.f('ix_assets_asset_category'), table_name='assets')
    op.drop_table('assets')
    # ### end Alembic commands ###
