"""Create collections table

Revision ID: 2e0c8e18e004
Revises: 8c563727f027
Create Date: 2026-08-31 19:34:43.513892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e0c8e18e004'
down_revision: Union[str, Sequence[str], None] = '8c563727f027'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('collection_code', sa.String(length=30), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('collection_date', sa.Date(), nullable=False),
    sa.Column('pickup_receipt_number', sa.String(length=50), nullable=True),
    sa.Column('source_type', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), server_default='scheduled', nullable=False),
    sa.Column('expected_item_count', sa.Integer(), nullable=True),
    sa.Column('transport_reference', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['location_id'], ['customer_locations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pickup_receipt_number')
    )
    op.create_index(op.f('ix_collections_collection_code'), 'collections', ['collection_code'], unique=True)
    op.create_index(op.f('ix_collections_customer_id'), 'collections', ['customer_id'], unique=False)
    op.create_index(op.f('ix_collections_location_id'), 'collections', ['location_id'], unique=False)
    op.create_index(op.f('ix_collections_status'), 'collections', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_collections_status'), table_name='collections')
    op.drop_index(op.f('ix_collections_location_id'), table_name='collections')
    op.drop_index(op.f('ix_collections_customer_id'), table_name='collections')
    op.drop_index(op.f('ix_collections_collection_code'), table_name='collections')
    op.drop_table('collections')
    # ### end Alembic commands ###
