"""Create asset sanitization history

Revision ID: 8bcd4c61fe86
Revises: 3e8c6a1b4d72
Create Date: 2026-09-07 11:13:08.049803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bcd4c61fe86'
down_revision: Union[str, Sequence[str], None] = '3e8c6a1b4d72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_sanitizations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('data_wipe_status', sa.String(length=40), nullable=False),
    sa.Column('data_wipe_method', sa.String(length=100), nullable=True),
    sa.Column('data_wipe_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data_wipe_reference', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_sanitizations_asset_id'), 'asset_sanitizations', ['asset_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_asset_sanitizations_asset_id'), table_name='asset_sanitizations')
    op.drop_table('asset_sanitizations')
    # ### end Alembic commands ###
