"""Create asset inspections table

Revision ID: cb856cbf1b40
Revises: 29f0f813dc72
Create Date: 2026-08-31 20:36:45.512368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb856cbf1b40'
down_revision: Union[str, Sequence[str], None] = '29f0f813dc72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_inspections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('inspection_type', sa.String(length=30), nullable=False),
    sa.Column('inspection_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('inspected_by', sa.String(length=150), nullable=True),
    sa.Column('working_status', sa.String(length=30), nullable=False),
    sa.Column('overall_condition', sa.String(length=30), nullable=False),
    sa.Column('display_condition', sa.String(length=30), nullable=False),
    sa.Column('body_condition', sa.String(length=30), nullable=False),
    sa.Column('keyboard_condition', sa.String(length=30), nullable=False),
    sa.Column('touchpad_condition', sa.String(length=30), nullable=False),
    sa.Column('hinge_condition', sa.String(length=30), nullable=False),
    sa.Column('ports_condition', sa.String(length=30), nullable=False),
    sa.Column('battery_condition', sa.String(length=30), nullable=False),
    sa.Column('charger_status', sa.String(length=30), nullable=False),
    sa.Column('ram_status', sa.String(length=30), nullable=False),
    sa.Column('storage_status', sa.String(length=30), nullable=False),
    sa.Column('cpu_status', sa.String(length=30), nullable=False),
    sa.Column('gpu_status', sa.String(length=30), nullable=False),
    sa.Column('accessories', sa.Text(), nullable=True),
    sa.Column('inspection_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_inspections_asset_id'), 'asset_inspections', ['asset_id'], unique=False)
    op.create_index(op.f('ix_asset_inspections_inspection_type'), 'asset_inspections', ['inspection_type'], unique=False)
    op.create_index(op.f('ix_asset_inspections_working_status'), 'asset_inspections', ['working_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_asset_inspections_working_status'), table_name='asset_inspections')
    op.drop_index(op.f('ix_asset_inspections_inspection_type'), table_name='asset_inspections')
    op.drop_index(op.f('ix_asset_inspections_asset_id'), table_name='asset_inspections')
    op.drop_table('asset_inspections')
    # ### end Alembic commands ###
