"""create QC template framework

Revision ID: d79ad011f32b
Revises: a2c1f9d4e6b7
Create Date: 2026-09-14 14:57:35.579333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd79ad011f32b'
down_revision: Union[str, Sequence[str], None] = 'a2c1f9d4e6b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qc_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('version >= 1', name='ck_qc_templates_version_positive'),
    sa.ForeignKeyConstraint(['category_id'], ['asset_categories.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_id', 'code', 'version', name='uq_qc_templates_category_code_version')
    )
    op.create_index('ix_qc_templates_category_id', 'qc_templates', ['category_id'], unique=False)
    op.create_index('ix_qc_templates_is_active', 'qc_templates', ['is_active'], unique=False)
    op.create_index('ux_qc_templates_active_category', 'qc_templates', ['category_id'], unique=True, postgresql_where=sa.text('is_active = true'))
    op.create_table('qc_template_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('item_code', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('response_type', sa.String(length=30), nullable=False),
    sa.Column('is_required', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('sort_order >= 0', name='ck_qc_template_items_sort_order_nonnegative'),
    sa.ForeignKeyConstraint(['template_id'], ['qc_templates.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_id', 'item_code', name='uq_qc_template_items_template_code')
    )
    op.create_index('ix_qc_template_items_sort_order', 'qc_template_items', ['sort_order'], unique=False)
    op.create_index('ix_qc_template_items_template_id', 'qc_template_items', ['template_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_qc_template_items_template_id', table_name='qc_template_items')
    op.drop_index('ix_qc_template_items_sort_order', table_name='qc_template_items')
    op.drop_table('qc_template_items')
    op.drop_index('ux_qc_templates_active_category', table_name='qc_templates', postgresql_where=sa.text('is_active = true'))
    op.drop_index('ix_qc_templates_is_active', table_name='qc_templates')
    op.drop_index('ix_qc_templates_category_id', table_name='qc_templates')
    op.drop_table('qc_templates')
    # ### end Alembic commands ###
